baseURL = "https://blog.thinegen.de"
title = "blog.thinegen.de"

theme = "schwarz"

enableRobotsTXT = true

pygmentscodefences = true
pygmentsoptions = "linenos=true"

enableGitInfo = true
rssLimit = 20
paginate = 20

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

PluralizeListTitles = false

pygmentsUseClasses = true

[minify]
  [minify.tdewolff]
      [minify.tdewolff.html]
        KeepQuotes = true

[markup]
  defaultMarkdownHandler = "goldmark"

[frontmatter]
  date = ["publishDate", "date", "lastmod"]

[permalinks]
  blog = "/:sections/:year/:month/:filename/"

[Params]
  giturl = "https://github.com/thinegen/blog"
  dateFormat = "2006-01-02"
  showCC = true
  showBY = true
  showSA = true
  sectionsToSortAlphabetically = ["projekte", "projects"]

[[languages.de.menu.main]]
  name = "Home"
  url = "/de/"
  weight = 1
[[languages.en.menu.main]]
  name = "Home"
  url = "/en/"
  weight = 1

  [[languages.de.menu.main]]
  name = "Blog"
  url = "/de/blog/"
  weight = 2
[[languages.en.menu.main]]
  name = "Blog"
  url = "/en/blog/"
  weight = 2

[[languages.de.menu.main]]
  name = "Shorts"
  url = "/de/shorts/"
  weight = 3
[[languages.en.menu.main]]
  name = "Shorts"
  url = "/en/shorts/"
  weight = 3

[[languages.de.menu.main]]
  name = "Projekte"
  url = "/de/projekte/"
  weight = 4
[[languages.en.menu.main]]
  name = "Projects"
  url = "/en/projects/"
  weight = 4

[languages]
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"
    languageCode = "de"
    [languages.de.params]
      imprintPage = "impressum.md"
      privacyPage = "datenschutz.md"
      copyrightPage = "copyright.md"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en"
    [languages.en.params]
      imprintPage = "imprint.md"
      privacyPage = "privacy.md"
      copyrightPage = "copyright.md"
