title = "thinegen.de"

theme = "schwarz"

enableRobotsTXT = true

pygmentscodefences = true
pygmentsoptions = "linenos=true"

enableGitInfo = true
rssLimit = 20
paginate = 20

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

PluralizeListTitles = false

pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[minify]
  [minify.tdewolff]
      [minify.tdewolff.html]
        KeepQuotes = true

[markup]
  defaultMarkdownHandler = "goldmark"

[frontmatter]
  date = ["publishDate", "date", "lastmod"]

[permalinks]
  blog = "/:sections/:year/:month/:filename/"
  shorts = "/:sections/:year/:month/:filename/"

[Params]
  giturl = "https://github.com/thinegen/web"
  dateFormat = "2006-01-02"
  showCC = true
  showBY = true
  showSA = true
  sectionsToSortAlphabetically = ["projekte", "projects"]
  noindexImages = true

[[languages.de.menu.main]]
  url = "/"
  name = "Home"
  weight = 1
[[languages.en.menu.main]]
  url = "/"
  name = "Home"
  weight = 1

  [[languages.de.menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[languages.en.menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[languages.de.menu.main]]
  name = "Shorts"
  url = "/shorts/"
  weight = 3
[[languages.en.menu.main]]
  name = "Shorts"
  url = "/shorts/"
  weight = 3

[[languages.de.menu.main]]
  name = "Projekte"
  url = "/projekte/"
  weight = 4
[[languages.en.menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4

[languages]
  [languages.de]
    baseURL = "https://thinegen.de"
    languageName = "Deutsch"
    contentDir = "content/de"
    languageCode = "de"
    [languages.de.params]
      imprintPage = "impressum.md"
      privacyPage = "datenschutz.md"
      copyrightPage = "copyright.md"
      description = "Ein paar Gedanken und Projekte zu den Themen, auf die ich gerade Lust habe."
  [languages.en]
    baseURL = "https://thinegen.com"
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en"
    [languages.en.params]
      imprintPage = "imprint.md"
      privacyPage = "privacy.md"
      copyrightPage = "copyright.md"
      description = "Projects I build and thoughts on things I am doing right now."
