name: build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Build Hugo site and deploy
        uses: aormsby/hugo-deploy-to-pages@v2
        with:
          hugo_publish_directory: 'public'
          source_branch: 'main'
          deploy_branch: 'live'
          commit_message: 'new build'
          hugo_build_options: '--minify'
          fresh_build: true
